---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}-svc
spec:
  ports:
  - name: "{{ .Values.env.api_port }}-{{ .Values.env.api_port }}"
    port: {{ .Values.env.api_port }}
    protocol: TCP
    targetPort: {{ .Values.env.api_port }}
  selector:
    app: {{ .Release.Name }}
  type: ClusterIP