---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pokescale-ingress
  namespace: pokescale
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: pokescale.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pokescale-svc
                port:
                  number: 8000
