name: docker-ci

on:
  push:
    branches: ['master']

jobs:
  testandbuild:

    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
    - name: check out code repro
      uses: actions/checkout@v3
      with: 
        repository: xamma/pokescale
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: master

    - name: setup python3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: install dependencies
      working-directory: ./src
      run: |
       python -m pip install --upgrade pip
       pip install flake8 pytest httpx
       if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      id: lint
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: test-pytest
      id: test
      working-directory: ./src/main
      run: |
       pytest

    - name: login to container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: build and push
      if: steps.test.outcome == 'success'
      uses: docker/build-push-action@v3
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: ghcr.io/xamma/pokescale:latest 